name: Clang format linter
on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './"Operating System"'
        extensions: 'cpp'
        clangFormatVersion: 16
